name: ariel
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_statusbarcolor: ^0.2.3
  # webview_flutter: ^0.3.20+2
  flutter_webview_plugin: ^0.3.11
  # share: ^0.6.4+3
  # flutter_launcher_icons: ^0.7.5
  # zoom_widget: ^0.1.3
  firebase_core: ^0.4.5
  # firebase_auth: ^0.16.1
  firebase_messaging: ^6.0.16
  firebase_analytics: ^5.0.14
  fluttertoast: ^4.0.1
  carousel_slider: ^2.1.0
  # photo_view: ^0.9.2
  # story_view: ^0.11.0
  dio: ^3.0.3
  video_player: ^0.10.11+2
  flutter_bloc: ^0.21.0
  json_serializable: ^3.2.3
  intl: ^0.16.0
  url_launcher: ^5.2.0
  cached_network_image: ^2.0.0-rc
  sliding_up_panel: ^1.0.2
  screenshot: ^0.2.0
  share_extend: ^1.1.9
  firebase_admob: ^0.9.3+4
  purchases_flutter: ^1.2.1
  shared_preferences: ^0.5.10


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay.otf
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
          weight: 500
        - asset: assets/fonts/Proxima Nova Thin.otf
          weight: 300
        - asset: assets/fonts/Proxima Nova Thin.otf
          weight: 400
        - asset: assets/fonts/Proxima Nova Bold.otf
          weight: 600
        - asset: assets/fonts/Proxima Nova Extrabold.otf
          weight: 700
        - asset: assets/fonts/Proxima Nova Black.otf
          weight: 800
        - asset: assets/fonts/Proxima Nova Black.otf
          weight: 900

    - family: JamIcons
      fonts:
        - asset: assets/fonts/JamIcons.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
